In [1]:
from dsc80_utils import *

In [19]:
cols = [
    # 'original_ID',
    'name',
    'store',
    'harmonized single category',
    'brand',
    'f_FPro',
    # 'f_FPro_P',
    # 'f_min_FPro',
    # 'f_std_FPro',
    'f_FPro_class',
    'price',
    'price percal',
    'package_weight',
    'has10_nuts',
    'is_Nuts_Converted_100g',
    'Protein',
    'Total Fat',
    'Carbohydrate',
    'Sugars, total',
    'Fiber, total dietary',
    # 'Calcium',
    # 'Iron',
    'Sodium',
    # 'Vitamin C',
    'Cholesterol',
    # 'Fatty acids, total saturated',
    # 'Total Vitamin A',
]
col_renames = {
    'harmonized single category': 'category',
    'f_FPro': 'FPro',
    'f_FPro_class': 'FPro_class',
}

In [28]:
def subset_and_rename(df):
    return df[cols].rename(columns=col_renames)

In [29]:
def filter_has10(df):
    return (
        df.query('has10_nuts == 1 and is_Nuts_Converted_100g == 1')
        .drop(columns=['has10_nuts', 'is_Nuts_Converted_100g'])
    )

In [30]:
df = (
    pd.read_csv('GroceryDB_foods.csv')
    .pipe(subset_and_rename)
    .pipe(filter_has10)
)
df

,name,store,category,brand,...,"Sugars, total","Fiber, total dietary",Sodium,Cholesterol
0,Stonyfield Organic Whole Milk Strawberry Beet ...,Target,baby-food,Stonyfield,...,9.09,0.00,0.08,0.01
1,Stonyfield Organic Whole Milk Pear Spinach Man...,Target,baby-food,Stonyfield,...,9.09,0.00,0.08,0.01
2,Once Upon a Farm Organic Mama Blueberry Fruit ...,Target,baby-food,Once Upon a Farm,...,7.69,2.20,0.01,0.00
...,...,...,...,...,...,...,...,...,...
50464,"Sabra Dark Chocolate Dessert Dip & Spread, 8 oz",Walmart,spread-squeeze,Sabra,...,21.43,3.57,0.14,0.00
50465,"MaraNatha, No Stir Peanut Butter, 1.15 oz Packets",Walmart,spread-squeeze,MaraNatha,...,3.12,6.25,0.20,0.00
50466,Great Value No Stir Creamy Natural Peanut Butt...,Walmart,spread-squeeze,Great Value,...,3.12,6.25,0.38,0.00

In [35]:
display_df(df.describe(), rows=8, cols=12)

,FPro,FPro_class,price,price percal,package_weight,Protein,Total Fat,Carbohydrate,"Sugars, total","Fiber, total dietary",Sodium,Cholesterol
count,26250.00,26250.00,22220.00,2.08e+04,24975.00,26250.00,26250.00,26250.00,26241.00,26241.00,26250.00,26250.00
mean,0.73,2.48,4.64,3.00e-02,461.08,8.69,12.98,35.30,11.88,3.23,21.75,0.03
std,0.23,1.03,3.73,3.53e-01,1934.76,8.96,14.68,176.90,16.70,5.34,3380.43,1.10
min,0.00,0.00,0.03,1.26e-05,0.53,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.62,3.00,2.50,2.93e-03,198.45,2.92,1.76,7.83,0.77,0.00,0.06,0.00
50%,0.79,3.00,3.79,5.74e-03,336.00,6.67,8.24,26.67,3.90,1.60,0.30,0.00
75%,0.91,3.00,5.69,1.17e-02,473.00,11.76,20.69,57.14,17.50,3.57,0.55,0.02
max,1.00,3.00,72.99,1.51e+01,272155.42,294.64,266.67,20000.00,181.82,157.89,547619.05,127.45

In [40]:
df.to_csv('../../resources/data/grocerydb.csv', index=False)

In [39]:
display_df(df[df['name'].str.contains('Hapi')], cols=16)

,name,store,category,brand,FPro,FPro_class,price,price percal,package_weight,Protein,Total Fat,Carbohydrate,"Sugars, total","Fiber, total dietary",Sodium,Cholesterol
16992,"Pure Punch Hapi Water 8ct, 48 fl oz",WholeFoods,drink-soft-energy-mixes,HAPI DRINKS,0.88,3.0,NaN,NaN,1440.00,0.00,0.00,2.78,0.00,0.00,0.00,0.0
34223,Hapi Hot Wasabi Peas 4.23oz,Target,produce-packaged,Hapi,0.92,3.0,2.19,1.90e-02,119.92,16.03,11.22,64.13,3.21,16.03,0.67,0.0
45432,"Hapi Snacks Wasabi Peas, Hot, 9.9 Oz",Walmart,snacks-mixes-crackers,Hapi,0.97,3.0,4.47,3.47e-03,280.66,14.11,14.11,63.49,14.11,3.53,0.30,0.0
45833,Hapi Sriracha Peas 9.9oz,Target,snacks-nuts-seeds,Hapi,0.95,3.0,4.69,1.88e-02,280.00,14.29,10.71,67.86,21.43,3.57,0.75,0.0
45834,Hapi Wasabi Green Peas 9.9oz,Target,snacks-nuts-seeds,Hapi,0.97,3.0,5.99,4.67e-03,280.00,14.11,14.11,63.49,14.11,3.53,0.30,0.0